apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwe
  template:
    metadata:
      labels:
        app: dwe
    spec:
      containers:
      - image: okteto.dev/dwe:latest
        name: dwe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2056a909-5c9d-4113-8ca6-1ae020d543fa"
        - name: Vless_Path
          value: "/pbiunf4"
        - name: Vmess_UUID
          value: "2056a909-5c9d-4113-8ca6-1ae020d543fa"
        - name: Vmess_Path
          value: "/yh57fhjbky"
        - name: Share_Path
          value: "/v2link"
